### Different technique to handle Imbalanced data

### Under Sampling Majority Class

- Class 1 : 9000 , Class 2 : 1000

- Randomly pick 1000 class from majority classes then fit 1000 rows from both classes into models.


### Over Sampling Minority Class

- Class 1 : 9000 , Class 2 : 1000

- Generate new sample from minority sample classes by simply duplicating them.


### Over Sampling Minority Class using SMOTE

- Generate synthetic examples using knn algorithm


### Ensemble Method

- Class1 : 3000 , Class2 : 1000

- Create batch=3 , take first 1000 from class1 and 1000 from class2 , Calculate accuracy .

- take second 1000 rows from class1 and calculate accuracy

- take third 1000 rows from class1 and calculate accuracy , then take majority voting.


### Focal Loss

- It will penalize majority samples during loss calculation and give more weights to minority class samples.




In [65]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split 

import warnings
warnings.filterwarnings('ignore')

In [66]:
df=pd.read_csv("C:\\Users\\Dell\\Data Science\\CampusX Tutorial\\Feature Engineering\\Pratical Implementation\\Feature Selection\\creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [67]:
df.shape 

(284807, 31)

In [68]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [69]:
X=df.drop("Class",axis=1)
y=df['Class']

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score
from sklearn.model_selection import GridSearchCV,KFold

In [71]:
model=LogisticRegression()

grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}

cv=KFold(n_splits=5,random_state=None,shuffle=False)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,
                                               random_state=1)

clf=GridSearchCV(model,grid,cv=cv,n_jobs=-1,scoring='f1_macro')

clf.fit(X_train,y_train)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [72]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[56851    24]
 [   36    51]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56875
           1       0.68      0.59      0.63        87

    accuracy                           1.00     56962
   macro avg       0.84      0.79      0.81     56962
weighted avg       1.00      1.00      1.00     56962



In [73]:
print(accuracy_score(y_test,y_pred))

0.9989466661985184


In [74]:
print(precision_score(y_test,y_pred))

0.68


In [75]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)
y_predict=classifier.predict(X_test)
print(accuracy_score(y_test,y_predict))

0.9995435553526912


In [76]:
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[56869     6]
 [   20    67]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56875
           1       0.92      0.77      0.84        87

    accuracy                           1.00     56962
   macro avg       0.96      0.89      0.92     56962
weighted avg       1.00      1.00      1.00     56962



In [77]:

# we can use class-weights hyperparameter tuning for random forest option
# to give diff weights for different classes.

class_weights=dict({0:1,1:100})
classifier=RandomForestClassifier(class_weight=class_weights)
classifier.fit(X_train,y_train)
y_predict=classifier.predict(X_test)
print(accuracy_score(y_test,y_predict))


0.9995786664794073


In [78]:
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[56871     4]
 [   20    67]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56875
           1       0.94      0.77      0.85        87

    accuracy                           1.00     56962
   macro avg       0.97      0.89      0.92     56962
weighted avg       1.00      1.00      1.00     56962



### UnderSampling 

In [79]:

# Undersampling will not work very well bec it will lose useful information.

from imblearn.under_sampling import NearMiss
from collections import Counter
Counter(y_train)

# Shows the count of values in y_train 

Counter({0: 227440, 1: 405})

In [80]:
ns=NearMiss(0.8)
X_train_ns,y_train_ns=ns.fit_resample(X_train,y_train)
print("No of classes before fit {}",format(Counter(y_train)))
print("No of classes after fit {}",format(Counter(y_train_ns)))

# 80 percent *  majority class = minority class.


No of classes before fit {} Counter({0: 227440, 1: 405})
No of classes after fit {} Counter({0: 506, 1: 405})


In [81]:
# Undersampling will work only where data is less .

classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [82]:
y_predict=classifier.predict(X_test)
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.8568694919419965
[[48729  8146]
 [    7    80]]
              precision    recall  f1-score   support

           0       1.00      0.86      0.92     56875
           1       0.01      0.92      0.02        87

    accuracy                           0.86     56962
   macro avg       0.50      0.89      0.47     56962
weighted avg       1.00      0.86      0.92     56962



### OverSampling 

In [83]:
from imblearn.over_sampling import RandomOverSampler

os=RandomOverSampler(0.75)
X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print("No of classes before fit {}",format(Counter(y_train)))
print("No of classes after fit {}",format(Counter(y_train_ns)))

# 50 percent of majority class = minority classes.


No of classes before fit {} Counter({0: 227440, 1: 405})
No of classes after fit {} Counter({0: 227440, 1: 170580})


In [84]:
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [85]:
y_predict=classifier.predict(X_test)
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.9995786664794073
[[56871     4]
 [   20    67]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56875
           1       0.94      0.77      0.85        87

    accuracy                           1.00     56962
   macro avg       0.97      0.89      0.92     56962
weighted avg       1.00      1.00      1.00     56962



### SMOTE Technique 

In [87]:
from imblearn.combine import SMOTETomek

os=SMOTETomek(0.75)
X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print("No of classes before fit {}",format(Counter(y_train)))
print("No of classes after fit {}",format(Counter(y_train_ns)))

KeyboardInterrupt: 

In [ ]:
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

In [ ]:
y_predict=classifier.predict(X_test)
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

### Ensemble Technique 

In [ ]:
from imblearn.ensemble import EasyEnsembleClassifier

ensembleasy=EasyEnsembleClassifier()
ensembleasy.fit(X_train,y_train)


In [ ]:
y_predict=ensembleasy.predict(X_test)
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))